fritzing/fritzing-app

src/mainwindow/mainwindow.cpp
src/mainwindow/mainwindow.h
src/partseditor/pemainwindow.cpp
src/sketch/sketchwidget.cpp
src/sketch/sketchwidget.h

Show width and hight of a mouse selection area in status bar.
More precise alternative to ruler part for simple part measurements.

Fixes fritzing/fritzing-app#2445

---

resources/templates/generic_dip_fzpTemplate.txt

generic_dip: use correct width in breadboard view

---

translations/fritzing_it.ts

* Fix typo in existing translation
* Add some missing translations

More Italian translations

---

src/items/ruler.cpp

Whats new!
1. Ruler is now either Metric or English.
2. Metric has 1/100 Centimeter scale for fine measurement. 
3. Changing "Units" will be reflected immediately on window.
4. No global class members or variables added. Should not interfere with other UI i believe.
Below pics show the dynamic changing of units, also I changed the 1/100 centimeter scale to just one side:
One improvement I thought of was not showing the 1/00 centimeter scale until you are really zoomed in? 
I tried to keep the UI as simple looking as possible using the old Ruler as guideline. Let me know if there is anything you want changed, I hope my layout is acceptable to everyone?

PCB ruler update

---

src/items/ruler.cpp
src/items/ruler.h

change inspector widget "units" combo box to radio buttons

---

src/main.cpp

These changes were required to compile latest master on Ubuntu 14.04.

Make compatible with Qt < 5.6

---

phoenix.pro
pri/boostdetect.pri
pri/libgit2detect.pri
pri/utils.pri

Update to "Support System Boost and libgit2"

---

translations/fritzing_pt_pt.ts

I have updated the european portuguese translation and added more data.
Please don't forget to update or make connection to the other languages, including the original english translation, to sync them all.
I will keep updating the translation soon.

Update fritzing european portuguese translation

---

translations/fritzing_sl.ts

Translete Fritzing to Slovenian
version 1.0

Slovenian translate

---

translations/fritzing_sl.ts

Update Slovenian Translate.

---

src/fapplication.cpp
src/fapplication.h

Type had to be changed because of updated QT version.

Fix server mode

---

src/fapplication.cpp

For details, have a look at this: https://github.com/fritzing/fritzing-app/issues/3308#issuecomment-351642253

Bugfix for macOS in parts db regeneration

---

Fritzing.sh
install_fritzing.sh
uninstall_fritzing.sh

A ton of improvements to installer script. Uninstall script coming soon.
Let me know if a bug in the script exists.

Improvements to install script.

---

install_fritzing.sh
uninstall_fritzing.sh

I tried to get finished with the uninstall script the fastest I can.
I will test the mechanism, and I will let you know if something has to be changed.

"Further" improvements to both scripts.

---

translations/fritzing_pl.ts

terrible ortographics error fixed

---

.travis.yml
tools/aws_tasks.sh
tools/release_fritzing.bat

Add continuous delivery for windows builds

Add windows cd

---

README.md

Cleanup Badges 

---

src/connectors/connector.cpp
src/connectors/connectorshared.cpp
src/fsvgrenderer.cpp
src/fsvgrenderer.h
src/items/itembase.cpp
src/items/itembase.h
src/items/paletteitembase.cpp
src/items/partlabel.cpp
src/items/partlabel.h
src/partsbinpalette/svgiconwidget.cpp
src/partsbinpalette/svgiconwidget.h
src/sketch/sketchwidget.cpp
src/sketch/sketchwidget.h
src/svg/svgfilesplitter.cpp
src/svg/svgfilesplitter.h
src/svg/svgpathparser.cpp
src/svg/svgpathparser.h
src/utils/bezier.cpp
src/utils/bezier.h
src/utils/graphicsutils.cpp
src/utils/graphicsutils.h

I was going to do this in multiple different pull requests but this is the result of looking at "expensive" functions and cleaning up corresponding classes.

Constexprification, NSDMIifying, and other code cleanup

---

src/sketch/pcbsketchwidget.cpp

Ignore breadboard and schema wires when setting pcb layer count

---

src/connectors/connectoritem.cpp

Cleaned up notes for one function inspected while researching cause for drc failures.
This is an initial sample to discuss, before I start doing pull requests for others I had my fingers in while researching the bugs. This one does not overlap the actual changes, so can be done before or after the pending bug fix pull request. Added the basic header that doxygen uses, a few comments to help keep track of context reading the code, and adjustments to match the published coding style.

doxygen, comments, code style for collectEqualPotential

---

src/connectors/connectoritem.cpp

This commit fixes #3616 
I hope that this does not break anything or causes performance issues (now all the connections of the breadboard are analysed).

fixes #3616

---

src/mainwindow/mainwindow_export.cpp

Fill image with the background before exporting, fixes #3261

---

resources/properties.xml

Hi,
I am not sure if I should add some of these values to the properties capacitance5mm, capacitance7.5mm, etc. When are they used? 
Cheers,
Andres

added more capacitor values, fixes 3713.

---

src/dialogs/recoverydialog.h
src/fsplashscreen.h
src/mainwindow/fritzingwindow.h
src/partsbinpalette/partsbinlistview.cpp
src/utils/folderutils.h

Fix deprecation warnings
