src/sketch/fgraphicsscene.cpp
src/sketch/fgraphicsscene.h
src/sketch/sketchwidget.cpp

This allows users to align items to one or more locked items. For example, if the user locks the PCB in the background, and then selects several components INCLUDING the locked PCB, all components will be (left | right | center) aligned to the PCB. If no selected items are locked, the aligning functions work as before.

Align to locked items (if any), otherwise align as usual.

---

src/items/partlabel.cpp
src/mainwindow/mainwindow_menu.cpp

Based on your suggestion, this should fix the degree symbol in all operating systems. (To be clear: I tested this in Mac OS and it looks good).

Fix degrees symbols in Mac OS, retain in Windows

---

src/main.cpp

Replace comma between versions with hyphen.
qDebug() automatically puts a single space between each item, and
outputs a newline at the end.
http://doc.qt.io/qt-5/qtglobal.html#qDebug

remove extra spaces and blank lines in --help

---

src/sketch/sketchwidget.cpp

This is just a little cleanup patchset as I was looking at other improvements. I noticed m_pasteOffset gets the negative of the negative of originalPos, which means originalPos has nothing to do with the drop event.

Remove unnecessary math from dropEvent

---

src/items/wire.cpp
src/items/wire.h
src/mainwindow/mainwindow.h
src/mainwindow/mainwindow_menu.cpp
src/sketch/breadboardsketchwidget.cpp
src/sketch/breadboardsketchwidget.h

As you probably know, several popular breadboarding kits come with premade jumper wires color-coded by length ([Radio Shack kit](https://www.radioshack.com/products/solderless-jumper-wire-kit), [SparkFun kit](https://www.sparkfun.com/products/124), [Elenco Kit](https://www.amazon.com/Elenco-Piece-Pre-formed-Jumper-Wire/dp/B0002H7AIG%3FSubscriptionId%3DAKIAILSHYYTFIVPWUY6Q%26tag%3Dduckduckgo-osx-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB0002H7AIG)). The color order is consistent between these kits, and it's the same as resistor color order.
When I am breadboarding in Fritzing, I like to logically color-code my wires — black for ground, read for VCC, etc — as I imagine most people do.
However, when the time comes to migrate my design from Fritzing breadboard to …

Add view option for "color wires by length"

---

src/svg/gerbergenerator.cpp

The original code has only one "end region" (G37) statement for the whole file, but has multiple "start region" (G36) commands. AFAIK this results in an incorrect gerber file. (I think that polarity changes (%LPC or %LPD) inside a region are also illegal, but I'm too lazy to search the specifications for that.) 
This change puts the "end region" (G37) statement at the end of each region.

close gerber regions properly (#3333)

---

src/fapplication.cpp
tools/deploy_fritzing_mac.sh

Deployment of Fritzing.app on OS X bombs out while trying to build the parts database. The crash happens inside `Fritzing -db foo`, which can’t set up its mouse pointers because it has no UI.
This patch skips does cursor initialization only if the service is `NoService`. Are there other conditions when we **do** want to bring up a GUI?
Tested very lightly.

Allow headless builds on OS X

---

src/utils/folderutils.cpp

On some win32 systems the bin search field does not appear in the "Parts view", please see [this Fritzing forum topic](http://forum.fritzing.org/t/search-function-in-the-parts-view-does-not-work/1536/65).
It looks like this happens because QDir::absoluteFilePath on win32 does not return an uppercase drive letter while other File/folder classes/methods do (i.e.: QFileInfo::absoluteFilePath).
Depending on the way the OS is configured or the app is started, some users reports this problem (like me), while most users don't.

solved win32 drive letter case sensitivity issue on some systems

---

install_fritzing.sh

I just added installation modes (user & system mode), since it will be handy to have it installled to the system. (The pre-made Ubuntu/Linux Mint package lacked the Fritzing icon) And I also removed 'sh' compatiblity. (C'mon! BASH 4 life!)

Improve install script.

---

src/utils/graphutils.cpp

These arrays were allocated with `new[]`, so they have to be deleted with `delete[]`. Otherwise you risk memory leaks.

Use delete[] where new[] was used for allocation

---

src/mainwindow/mainwindow.cpp

This code seems to fix issue #3382 where a corrupted fzp file causes a seg fault in Fritzing and leaves the parts files around after the crash. While I don't know what I'm doing and just copied a section of code that deals with a similar situation and it would be good to have someone familiar with the code review this, since the alternative is a seg fault and a hang, I don't see that this fix could be worse.
Peter

fix bad part hangs Fritzing bug

---

resources/ratsnestcolors.xml

Orange has a cyan rgb hex as one of it's obsolete colors. Saved cyan rgb
values are occasionally becoming orange as it matches them with orange.
This should resolve #3296

Fix invalid obsolete orange color causing cyan to turn orange on load.

---

src/fapplication.cpp
src/referencemodel/sqlitereferencemodel.cpp
src/utils/folderutils.cpp
src/utils/folderutils.cpp.autosave
tools/linux_release_script/release.sh

This should fix a few errors that might appear when loading parts:
1. Relative paths specified on CLI caused problems
2. Recover from zero sized parts.db
3. Recover from missing parts.db
4. Avoid leaving zero sized parts.db, created valid parts.db when recovering.

Part handling

---

translations/syntax/styles.xml

Fixes code symbol invisibility in v0.9.3 on OSX10.12.6

Add symbol color to styles.xml

---

src/mainwindow/mainwindow.cpp
src/mainwindow/mainwindow.h
src/mainwindow/mainwindow_menu.cpp

This sounds a bit more optimistic than it should be.
First, some range checking is added, which prevents the mazerouter from totally corrupting memory (which it usually does, even if you don't see immediate crashes). Second, we disable the mazerouter.

Mazerouter fixes

---

src/mainwindow/mainwindow.cpp
src/mainwindow/mainwindow.h
src/mainwindow/mainwindow_menu.cpp
src/partseditor/pemainwindow.cpp
src/partseditor/pemainwindow.h

This fixes issue 3383 where when a new part is created with parts editor, the filenames didn't get copied across to alien_files in the main thread. Since I'm new to both c++ and Qt someone experienced needs to look over the fix and make sure it is appropriate.

Make pe delete part files on exit

---

src/items/clipablewire.cpp

As per issue https://github.com/fritzing/fritzing-app/issues/3128 and https://github.com/fritzing/fritzing-app/issues/3316 traces did not always connect to the pad. This was made worse when using large traces. http://forum.fritzing.org/t/very-bad-bug-incorrect-track-lenght-for-large-tracks/5008/29
It turns out the same math was being applied to the clipping in two places.
In clipablewire.cpp
`GraphicsUtils::shortenLine(p1, p2, c1->calcClipRadius() + (m_pen.width() / 2.0), 0);`
Which was sending the clipped data to shortenLine in connectoritem.cpp
`		return radius() - (strokeWidth() / 2.0);`
It looks like (m_pen.width() / 2.0) does the same thing as (strokeWidth() / 2.0) causing the path to be too short.
This patch fixes the above issues but exacerbates this issue …

Start trace at center of connection point

---

src/utils/textutils.cpp
src/utils/textutils.h
tests/auto/test_textutils/test_textutils.cpp
tests/auto/test_textutils/test_textutils.pro

With latest InkScape and Fritzing releases, one receives an error loading a schematic SVG, as reported here: http://forum.fritzing.org/t/font-error-in-parts-editor-when-reading-schematic-svg-which-is-edited-with-inkscape/3753
The problem is the SVG font fixing handles single quotes in the font-family attribute, but not inside the style attribute. The minimal fix was to update the regex in `removeFontFamilySingleQuotes` accordingly to support both.

Fix SVG font handling for single-quoted font-family inside style attribute

---

src/items/resistor.cpp
src/items/resistor.h

Increased the precision of the resistor values regex to 10 digits before the decimal and 5 digits after the decimal. Also added 1G ohm to the default set for good measure. Did some slight ctor cleanup as well. See #3292 for more information.

Fix the number of allowed digits within the resistor regex

---

pri/gitversion.pri

MacOS uses BSD-compatible date, which doesn't have the `--iso-8601` option.

Fix BUILD_DATE for MacOS

---

src/version/partschecker.cpp

Until now, the check only considers the minor version number, so it breaks with versions greater than 0.99.

Fix libgit2 version check to allow building with versions >= 1.0

---

.travis.yml
pri/boostdetect.pri
tests/auto/test_svg/test_svg.pro
tests/auto/test_textutils/test_textutils.pro

I found that the existing unit test `.pro` files had boost_1_70_0 hard-coded for the boost environment. That broke for me, since boost_1_72_0 is being used locally. Trying to get generic detection to work, so that the same boost environment (detection logic) would be used for both phoenix and the unit tests, I discovered that the relative path detected and used by pri/boostdetect.pri did not work for the unit tests. The folder nest level paths do not match the detected path.
I created a new boostdetect version (near rewrite) that takes an optional flag to generate an absolute path. An older version of pri/boostdetect.pri was unconditionally setting an absolute path. That was changed to relative at the same time that the detection search was expanded to look for the boost environment …

remove need for hard-coded boost path with unit tests

---

tests/auto/test_svg/test_pathlexer_protected.cpp
tests/auto/test_svg/test_pathlexer_public.cpp
tests/auto/test_svg/test_pathparse.cpp
tests/auto/test_svg/test_svg.pro

Unit tests for the low level svg path parsing Fritzing classes. The failures from test_pathparse.cpp are the important ones. That is the cause for #3647. The others are (currently) cosmetic, and avoided by preprocessing before parsing starts.

Svg parse tests

---

src/commands.cpp
src/sketch/sketchwidget.cpp

This fixes the following use case:
Add two parts into an empty project,
one of them with a bendable leg (for example a resistor)
Go to the PCB view, connect the parts.
Go to the breadboard view. You see a ratsnest line
for the unrouted connection. Grab the bendable leg
at its endpoint and move it.
The connection is separated in breadboard view,
and not in PCB view, resulting in the view being
out of sync. The fix will keep this kind
of connections. The same applies for schematic view
instead of PCV view.

Fix issue #3683

---

translations/fritzing_de.ts

Corrected from "habben" to "haben".

A typo in german translation #3694 - Bug correction

---

src/mainwindow/mainwindow_export.cpp

The items are deselected, but they can be still be seen as selected in the app. After the screen is refreshed (f. ex. by zooming in the app or moving a component), they are shown correctly.

Deselect all items before exporting an image to PNG or JPG. Fixes  #3712

---

src/mainwindow/mainwindow_export.cpp

I just call update, but calling item->setCacheMode(QGraphicsItem::NoCache) also works (even though the items does not have cache by default...)

force a paint of the item as there were issues when toggling layers.

---

src/items/symbolpaletteitem.cpp
src/items/symbolpaletteitem.h

This fixes the phantom ratsnest connections that appear when using net labels. It has not been tested thoroughly with other examples, in particular with power symbols (voltage) as they the same class.

fixes net labels, issues #3340 and  #2308.
